### ISSUE TITLE
Completed module 7 assignments

### ISSUE THREAD

**Issue by stacianordin** [ds4owd-001/md-07-assignments-StaciaNordin#1]
@larnsce @mianzg @sskorik01
I need to do this over and over and over again until I can understand, speak, and write the language.

**Comment by mianzg** [comment]
@stacianordin you did it great! Would you let us know what was the difficult parts to understand? Do you still have lingering questions?

**Comment by stacianordin** [comment]
I can read the code really well and it all makes sense, but when I'm asked to write something I forget which operator to use and when there is an = or an == or whatever.  It is just practice until it becomes normal.  I need to write everything I've learned into one cheat sheet to refer to.

**Comment by sskorik01** [comment]
That's good progress! And it's normal not to remember all the syntax in detail, that's why the documentation (and search browsers) exist!
